
#!/bin/bash
# =============================================================================
# Script Name: setup-network.sh
# Author: gnu-coffee
# Created: 2025-08-14
# Last Modified: 2025-08-14
# Description: Detect distro [Debian/Ubuntu is Accepted], configure DHCP network, enable & restart service
# License: MIT License
# =============================================================================

# --- Variables ---
SCRIPT_DIR="$(pwd)"
LOG_FILE="${SCRIPT_DIR}/network_setup.log"

# --- Color codes ---
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# --- Marker functions ---
function info() { echo -e "${YELLOW}[*] $1${NC}"; echo "[*] $1" >> "$LOG_FILE"; }
function success() { echo -e "${GREEN}[+] $1${NC}"; echo "[+] $1" >> "$LOG_FILE"; }
function error() { echo -e "${RED}[-] $1${NC}"; echo "[-] $1" >> "$LOG_FILE"; }

# --- Log header ---
echo "=== Network Setup Log ===" >> "$LOG_FILE"
echo "Execution Date: $(date '+%Y-%m-%d %H:%M:%S')" >> "$LOG_FILE"

# --- Root check ---
if [[ $EUID -ne 0 ]]; then
    error "This script must be run as root!"
    exit 1
fi

# --- Detect primary network interface ---
info "Detecting primary network interface..."
IFACE=$(ip -o link show | awk -F': ' '{print $2}' | grep -v '^lo$' | head -n 1)

if [ -z "$IFACE" ]; then
    error "No active network interface detected!"
    exit 1
fi
success "Detected interface: $IFACE"

# --- Detect Distro ---
if [ -f /etc/os-release ]; then
    . /etc/os-release
    DISTRO=$ID
else
    error "Cannot detect OS. Exiting."
    exit 1
fi

info "Detected OS: $DISTRO"

case "$DISTRO" in
    debian)
        info "Configuring DHCP using /etc/network/interfaces for Debian..."
        # Backup
        [ -f /etc/network/interfaces ] && cp /etc/network/interfaces /etc/network/interfaces.bak.$(date +%s)
        cat <<EOF > /etc/network/interfaces
# Auto-generated by setup-network.sh
auto lo
iface lo inet loopback

auto $IFACE
iface $IFACE inet dhcp
EOF
        success "/etc/network/interfaces updated."
        info "Enabling and restarting networking..."
        systemctl enable networking >>"$LOG_FILE" 2>&1
        systemctl restart networking >>"$LOG_FILE" 2>&1
        success "Networking restarted for Debian."
        ;;
    ubuntu)
        info "Configuring DHCP using netplan for Ubuntu..."
        NETPLAN_FILE="/etc/netplan/01-netcfg.yaml"
        [ -f "$NETPLAN_FILE" ] && cp "$NETPLAN_FILE" "$NETPLAN_FILE.bak.$(date +%s)"
        cat <<EOF > "$NETPLAN_FILE"
# Auto-generated by setup-network.sh
network:
  version: 2
  ethernets:
    $IFACE:
      dhcp4: true
EOF
        success "Netplan configuration written."
        info "Applying netplan..."
        netplan apply >>"$LOG_FILE" 2>&1
        success "Networking applied for Ubuntu."
        ;;
    *)
        error "Unsupported distro: $DISTRO. Exiting without changes."
        exit 1
        ;;
esac

success "Network configuration completed successfully."
echo -e "${GREEN}[+] See log file for details: $LOG_FILE${NC}"
